name: Create Image Rabbit Monitor

#runs when create a release 
on:
  release:
    types: [created]    

jobs:
  create-image:
    name: Create Image Rabbit Monitor
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Get commit hash
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Create version file
        shell: bash
        run: |
          echo '{"version": "${{ github.event.release.tag_name }}-${{ steps.vars.outputs.sha_short }}"}' > ./version.json
          cat ./version.json

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
  
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  
      - name: Build
        id: build_and_push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            regisleandro/rabbit-monitor:${{ github.event.release.tag_name }}
            regisleandro/rabbit-monitor:latest
